export const PATH_TO_CHARACTER_DATA = ['resources', 'character', 'data']
export const EXTERNAL_PATH_TO_CHARACTER_SPLASH = ['public','images', 'character', 'splash']
export const LOCAL_PATH_TO_CHARACTER_SPLASH = ['images', 'character', 'splash']
export const EXTERNAL_PATH_TO_CHARACTER_ICONS = ['public', 'images', 'character', 'icon']
export const LOCAL_PATH_TO_CHARACTER_ICONS = ['images', 'character', 'icon']